Description of set
Home > ImageComponentParser > GUILayout-v1p13 > +uiextras > set.m
set
PURPOSE
uiextras.set Store a default property value in a parent object
SYNOPSIS
function set(hObj, propName, propValue)
DESCRIPTION
uiextras.set  Store a default property value in a parent object
   uiextras.set(hObj,propName,propValue) stores a default property value
   in the object hObj such that children created inside it of the correct
   class will use the specified value (propValue) for the specified
   property by default. The property name should take the form
   "DefaultClassProperty", for example to set the default "TitleColor" for
   the class "uiextras.BoxPanel", use "DefaultBoxPanelTitleColor". Note
   that using the special object handle 0 sets the default for all new
   figures.
   Examples:
   >> uiextras.set( gcf(), 'DefaultBoxPanelTitleColor', 'g' )
   >> uiextras.set( 0, 'DefaultHBoxPadding', 5 )
   See also: uiextras.get
             uiextras.unset
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BoxPanel BoxPanel Show one element inside a box panel
CardPanel CardPanel Show one element (card) from a list
Container Container Container base class
DecoratedPanel DecoratedPanel Abstract panel class that manages fonts and colors
Empty Empty Create an empty space
Grid Grid Container with contents arranged in a grid
GridFlex GridFlex Container with contents arranged in a resizable grid
HBox HBox Arrange elements in a single horizontal row
HBoxFlex HBoxFlex A dynamically resizable horizontal layout
HButtonBox HButtonBox Arrange buttons horizontally in a single row
MousePointerHandler MousePointerHandler A class to handle mouse-over events
Panel Panel Show one element inside a panel
TabPanel TabPanel Show one element inside a tabbed panel
VBox VBox Arrange elements vertically in a single column
VBoxFlex VBoxFlex A dynamically resizable vertical layout
VButtonBox VButtonBox Arrange buttons vertically in a single column
makeFlexDivider makeFlexDivider Create a divider widget and add markings if desired
SOURCE CODE
function set(hObj, propName, propValue)
%uiextras.set  Store a default property value in a parent object
%
%   uiextras.set(hObj,propName,propValue) stores a default property value
%   in the object hObj such that children created inside it of the correct
%   class will use the specified value (propValue) for the specified
%   property by default. The property name should take the form
%   "DefaultClassProperty", for example to set the default "TitleColor" for
%   the class "uiextras.BoxPanel", use "DefaultBoxPanelTitleColor". Note
%   that using the special object handle 0 sets the default for all new
%   figures.
%
%   Examples:
%   >> uiextras.set(gcf(), 'DefaultBoxPanelTitleColor', 'g')
%   >> uiextras.set(0, 'DefaultHBoxPadding', 5)
%
%   See also: uiextras.get
%             uiextras.unset
%   Copyright 2010 The MathWorks, Inc.
%   $Revision: 1$
%   $Date: 2010-05-18$
% Check inputs
error(nargchk(3, 3, nargin, 'struct'))
if isa(hObj, 'uiextras.Container')
    hObj = double( hObj );
end
if ~isequal(hObj, 0) && ~ishghandle(hObj)
    error( 'GUILayout:InvalidArgument', 'Object must be a valid Handle Graphics object.' )
end
if ~ischar(propName)
    error( 'GUILayout:InvalidArgument', 'Property name must be a string.' )
end
% Make sure the property requested is a default
if ~strncmp(propName, 'Default', 7)
    error( 'GUILayout:InvalidArgument', 'Property name must begin with ''Default''.' )
end
% All OK, so set it
setappdata(hObj, propName, propValue);